### ISSUE TITLE
Holidays setting

### ISSUE THREAD

**Issue by cennini** [JostBaron/redmine_workload#18]
Is there any way to specify an holiday as Christmas or Easter or local holidays, like April 25th or May 1st in Italy ?  
Thanks a lot 
Alberto

**Comment by xJom** [comment]
Maybe it could be a good idea to align it to the Schedules-plugin instead?

https://github.com/Yoru94/redmine3.1-schedules-plugin

**Comment by braini75** [comment]
Now there is Basic Holiday and vacation Support included.
