### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by cennini** [JostBaron/redmine_workload#21]
I experienced same internal error chancing date windows. These are the informations I find in log file:
Started GET "/redmine/work_load/show?utf8=%E2%9C%93&workload%5Bfirst_day%5D=2014-05-16&workload%5Blast_day%5D=2014-05-23&workload%5Bstart_date%5D=2014-05-21&workload%5Busers%5D%5B%5D=8&workload%5Busers%5D%5B%5D=12" for 127.0.0.1 at 2014-05-26 11:14:09 +0200
Processing by WorkLoadController#show as HTML
  Parameters: {"utf8"=>"âœ“", "workload"=>{"first_day"=>"2014-05-16", "last_day"=>"2014-05-23", "start_date"=>"2014-05-21", "users"=>["8", "12"]}}
  Current user: amministratore (id=16)
Completed 500 Internal Server Error in 14ms

Could sameone give me any help ? 
Thanks
Alberto

**Comment by braini75** [comment]
Please, check out our current Version if this error still exist!

**Comment by braini75** [comment]
Not heard back. I guess it is solved!
