### ISSUE TITLE
Seems to be not compatible to Redmine 3.0.1

### ISSUE THREAD

**Issue by The-Judge** [JostBaron/redmine_workload#29]
This is what one gets when trying to use the plugin with Redmine 3.0.1:

Migrating plugins. Please be patient, this could take a while...
An error occurred while loading the routes definition of redmine_workload plugin (/home/redmine/redmine/plugins/redmine_workload/config/routes.rb): You should not use the `match` method in your router without specifying an HTTP method.
If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
If you want to expose your action to GET, use `get` in the router:
  Instead of: match "controller#action"
  Do: get "controller#action".

**Comment by braini75** [comment]
You can try the current development branch: https://github.com/JostBaron/redmine_workload/tree/feature/groupselect
It is working with 3.0.1. and will become the next master (hopefully soon).

Braini.

**Comment by The-Judge** [comment]
Hi Braini,

I confirm this is working. Thanks.
